export default function handler(req, res) {
  res.status(200).json([
    {
      id: 1,
      name: "Fontana Campestres",
      minPrice: "120",
      maxPrice: "160",
      imgProject: "/images/fontana-desktop.png",
      minBeds: "3",
      maxBeds: "4",
      minBaths: "3",
      maxBaths: "4",
    },
    {
      id: 2,
      name: "La Florida",
      minPrice: "120",
      maxPrice: "160",
      imgProject: "/images/fontana-desktop.png",
      minBeds: "3",
      maxBeds: "4",
      minBaths: "3",
      maxBaths: "4",
    },
    {
      id: 3,
      name: "Forteza I",
      minPrice: "120",
      maxPrice: "160",
      imgProject: "/images/fontana-desktop.png",
      minBeds: "3",
      maxBeds: "4",
      minBaths: "3",
      maxBaths: "4",
    },
    {
      id: 4,
      name: "Campo Alegre",
      minPrice: "120",
      maxPrice: "160",
      imgProject: "/images/fontana-desktop.png",
      minBeds: "3",
      maxBeds: "4",
      minBaths: "3",
      maxBaths: "4",
    },
    {
      id: 5,
      name: "La Florida II",
      minPrice: "120",
      maxPrice: "160",
      imgProject: "/images/fontana-desktop.png",
      minBeds: "3",
      maxBeds: "4",
      minBaths: "3",
      maxBaths: "4",
    },
    {
      id: 6,
      name: "Forteza II",
      minPrice: "120",
      maxPrice: "160",
      imgProject: "/images/fontana-desktop.png",
      minBeds: "3",
      maxBeds: "4",
      minBaths: "3",
      maxBaths: "4",
    },
    {
      id: 7,
      name: "Fontana Campestres",
      minPrice: "120",
      maxPrice: "160",
      imgProject: "/images/fontana-desktop.png",
      minBeds: "3",
      maxBeds: "4",
      minBaths: "3",
      maxBaths: "4",
    },
    {
      id: 8,
      name: "La Florida",
      minPrice: "120",
      maxPrice: "160",
      imgProject: "/images/fontana-desktop.png",
      minBeds: "3",
      maxBeds: "4",
      minBaths: "3",
      maxBaths: "4",
    },
    {
      id: 9,
      name: "Fontana Campestres",
      minPrice: "120",
      maxPrice: "160",
      imgProject: "/images/fontana-desktop.png",
      minBeds: "3",
      maxBeds: "4",
      minBaths: "3",
      maxBaths: "4",
    },
  ]);
}
